In [1]:
# import packages

import pandas as pd
import sqlalchemy as sa
from sqlalchemy import create_engine, MetaData, Table, Column, Integer, String, Float, NVARCHAR

In [13]:
# create SQL database

engine = create_engine('sqlite:////Users/arpanganguli/Documents/Professional/Projects/SINE/Database/CCS.db', echo = True) # sqlite:////absolute/path/to/file.db

meta = MetaData()

CCS = Table(
    'CCS', meta
    ,Column('Serial No', Float)
    ,Column('Round No.', Float)
    ,Column('Period', NVARCHAR)
    ,Column('City', NVARCHAR)
    ,Column('Age', NVARCHAR)
    ,Column('Gender', NVARCHAR)
    ,Column('Occupation of Respondent', NVARCHAR)
    ,Column('Annual Income', NVARCHAR)
    ,Column('No. of Family Members', NVARCHAR)
    ,Column('Education Qualification', NVARCHAR)
    ,Column('Number Of Earning Members', NVARCHAR)
    ,Column('Perception on General Economic Condition – compared to one year ago', NVARCHAR)
    ,Column('Outlook on General Economic Condition – one year ahead', NVARCHAR)
    ,Column('Perception on Household Circumstances – compared to one year ago', NVARCHAR)
    ,Column('Outlook on Household Circumstances – one year ahead', NVARCHAR)
    ,Column('Perception on Household Income – compared to one year ago', NVARCHAR)
    ,Column('Outlook on Household Income – one year ahead', NVARCHAR)
    ,Column('Perception on Household Spending – compared to one year ago', NVARCHAR)
    ,Column('Outlook on Household Spending – one year ahead', NVARCHAR)
    ,Column('Perception on Employment Scenario – compared to one year ago', NVARCHAR)
    ,Column('Outlook on Employment Scenario – one year ahead', NVARCHAR)
    ,Column('Perception on General Price Levels – compared to one year ago', NVARCHAR)
    ,Column('Outlook on General Price Levels – one year ahead', NVARCHAR)
    ,Column('Perception on Inflation – compared to one year ago', NVARCHAR)
    ,Column('Outlook on Inflation – one year ahead', NVARCHAR)
    )

meta.create_all(engine)

2021-02-22 23:32:03,078 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2021-02-22 23:32:03,079 INFO sqlalchemy.engine.base.Engine ()
2021-02-22 23:32:03,081 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2021-02-22 23:32:03,081 INFO sqlalchemy.engine.base.Engine ()
2021-02-22 23:32:03,082 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("CCS")
2021-02-22 23:32:03,083 INFO sqlalchemy.engine.base.Engine ()

In [11]:
# import files

url = r'/Users/arpanganguli/Documents/Professional/Projects/SINE/Database/CCS/CCS_201209.xlsx'
df = pd.read_excel(url)
display(df.head(5))

,Serial No,Round No.,Period,City,Age,Gender,Occupation of Respondent,Annual Income,No. of Family Members,Education Qualification,...,Perception on Household Income – compared to one year ago,Outlook on Household Income – one year ahead,Perception on Household Spending – compared to one year ago,Outlook on Household Spending – one year ahead,Perception on Employment Scenario – compared to one year ago,Outlook on Employment Scenario – one year ahead,Perception on General Price Levels – compared to one year ago,Outlook on General Price Levels – one year ahead,Perception on Inflation – compared to one year ago,Outlook on Inflation – one year ahead
0,1.0,10.0,SEP-12,Delhi,30-39,Male,Self employed/Business,Rs. 1 - 3 lakhs,5 and more,Below Graduate,...,Decreased,Decrease,Decreased,Decrease,Worsen,Will worsen,Gone up,Will go up,More than last year,More than current year
1,2.0,10.0,SEP-12,Mumbai,30-39,Female,Self employed/Business,Rs. 3 - 5 lakhs,5 and more,Below Graduate,...,Increased,Increase,Increased,Increase,Improved,Will improve,Gone up,Will go up,More than last year,More than current year
2,3.0,10.0,SEP-12,Bengaluru,22-29,Female,Self employed/Business,Rs. 1 - 3 lakhs,3 or 4,Up to primary,...,Remained the same,Remain the same,Remained the same,Increase,Improved,Will improve,Gone up,Will go up,More than last year,More than current year
3,4.0,10.0,SEP-12,Bengaluru,40-59,Male,Self employed/Business,Rs. 1 - 3 lakhs,3 or 4,Below Graduate,...,Remained the same,Remain the same,Increased,Increase,Remained the same,Will Remain the Same,Gone up,Will go up,More than last year,More than current year
4,5.0,10.0,SEP-12,Mumbai,40-59,Female,House wife,Rs. 1 - 3 lakhs,5 and more,Below Graduate,...,Increased,Increase,Increased,Neither increase nor decrease,Improved,Will improve,Gone up,Will go up,More than last year,More than current year

In [12]:
df.to_sql('CCS_Data', con=engine)

2021-02-22 23:31:44,644 INFO sqlalchemy.engine.base.Engine PRAGMA main.table_info("CCS_Data")
2021-02-22 23:31:44,644 INFO sqlalchemy.engine.base.Engine ()
2021-02-22 23:31:44,645 INFO sqlalchemy.engine.base.Engine PRAGMA temp.table_info("CCS_Data")
2021-02-22 23:31:44,646 INFO sqlalchemy.engine.base.Engine ()
2021-02-22 23:31:44,650 INFO sqlalchemy.engine.base.Engine
CREATE TABLE "CCS_Data" (
	"index" BIGINT,
	"Serial No" FLOAT,
	"Round No." FLOAT,
	"Period" TEXT,
	"City" TEXT,
	"Age" TEXT,
	"Gender" TEXT,
	"Occupation of Respondent" TEXT,
	"Annual Income" TEXT,
	"No. of Family Members" TEXT,
	"Education Qualification" TEXT,
	"Number Of Earning Members" FLOAT,
	"Perception on General Economic Condition – compared to one year ago" TEXT,
	"Outlook on General Economic Condition – one year ahead" TEXT,
	"Perception on Household Circumstances – compared to one year ago" TEXT,
	"Outlook on Household Circumstances – one year ahead" TEXT,
	"Perception on Household Income – compared to one year ago" TEXT,
	"Outlook on Household Income – one year ahead" TEXT,
	"Perception on Household Spending – compared to one year ago" TEXT,
	"Outlook on Household Spending – one year ahead" TEXT,
	"Perception on Employment Scenario – compared to one year ago" TEXT,
	"Outlook on Employment Scenario – one year ahead" TEXT,
	"Perception on General Price Levels – compared to one year ago" TEXT,
	"Outlook on General Price Levels – one year ahead" TEXT,
	"Perception on Inflation – compared to one year ago" TEXT,
	"Outlook on Inflation – one year ahead" TEXT
)


2021-02-22 23:31:44,651 INFO sqlalchemy.engine.base.Engine ()
2021-02-22 23:31:44,652 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-22 23:31:44,653 INFO sqlalchemy.engine.base.Engine CREATE INDEX "ix_CCS_Data_index" ON "CCS_Data" ("index")
2021-02-22 23:31:44,653 INFO sqlalchemy.engine.base.Engine ()
2021-02-22 23:31:44,655 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-22 23:31:44,669 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2021-02-22 23:31:44,742 INFO sqlalchemy.engine.base.Engine INSERT INTO "CCS_Data" ("index", "Serial No", "Round No.", "Period", "City", "Age", "Gender", "Occupation of Respondent", "Annual Income", "No. of Family Members", "Education Qualification", "Number Of Earning Members", "Perception on General Economic Condition – compared to one year ago", "Outlook on General Economic Condition – one year ahead", "Perception on Household Circumstances – compared to one year ago", "Outlook on Household Circumstances – one year ahead", "Perception on Household Income – compared to one year ago", "Outlook on Household Income – one year ahead", "Perception on Household Spending – compared to one year ago", "Outlook on Household Spending – one year ahead", "Perception on Employment Scenario – compared to one year ago", "Outlook on Employment Scenario – one year ahead", "Perception on General Price Levels – compared to one year ago", "Outlook on General Price Levels – one year ahead", "Perception on Inflation – compared to one year ago", "Outlook on Inflation – one year ahead") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2021-02-22 23:31:44,742 INFO sqlalchemy.engine.base.Engine ((0, 1.0, 10.0, 'SEP-12', 'Delhi', '30-39', 'Male', 'Self employed/Business', 'Rs. 1 - 3 lakhs', '5 and more', 'Below Graduate', 1.0, 'Remained the same', 'Will Remain the Same', 'Somewhat worse off', 'Will Remain the Same', 'Decreased', 'Decrease', 'Decreased', 'Decrease', 'Worsen', 'Will worsen', 'Gone up', 'Will go up', 'More than last year', 'More than current year'), (1, 2.0, 10.0, 'SEP-12', 'Mumbai', '30-39', 'Female', 'Self employed/Business', 'Rs. 3 - 5 lakhs', '5 and more', 'Below Graduate', 2.0, 'Improved', 'Will Improve', 'Somewhat better off', 'Will be better off', 'Increased', 'Increase', 'Increased', 'Increase', 'Improved', 'Will improve', 'Gone up', 'Will go up', 'More than last year', 'More than current year'), (2, 3.0, 10.0, 'SEP-12', 'Bengaluru', '22-29', 'Female', 'Self employed/Business', 'Rs. 1 - 3 lakhs', '3 or 4', 'Up to primary', 1.0, 'Improved', 'Will Improve', 'Difficult to say', 'Will Remain the Same', 'Remained the same', 'Remain the same', 'Remained the same', 'Increase', 'Improved', 'Will improve', 'Gone up', 'Will go up', 'More than last year', 'More than current year'), (3, 4.0, 10.0, 'SEP-12', 'Bengaluru', '40-59', 'Male', 'Self employed/Business', 'Rs. 1 - 3 lakhs', '3 or 4', 'Below Graduate', 3.0, 'Improved', 'Will Improve', 'Somewhat better off', 'Will be better off', 'Remained the same', 'Remain the same', 'Increased', 'Increase', 'Remained the same', 'Will Remain the Same', 'Gone up', 'Will go up', 'More than last year', 'More than current year'), (4, 5.0, 10.0, 'SEP-12', 'Mumbai', '40-59', 'Female', 'House wife', 'Rs. 1 - 3 lakhs', '5 and more', 'Below Graduate', 2.0, 'Improved', 'Will Improve', 'Somewhat better off', 'Will be better off', 'Increased', 'Increase', 'Increased', 'Neither increase nor decrease', 'Improved', 'Will improve', 'Gone up', 'Will go up', 'More than last year', 'More than current year'), (5, 6.0, 10.0, 'SEP-12', 'Mumbai', '30-39', 'Female', 'House wife', 'Rs. 1 lakh or less', '3 or 4', 'Up to primary', 1.0, 'Remained the same', 'Will Remain the Same', 'Somewhat better off', 'Will be better off', 'Remained the same', 'Remain the same', 'Increased', 'Neither increase nor decrease', 'Improved', 'Will improve', 'Gone up', 'Will go up', 'More than last year', 'More than current year'), (6, 7.0, 10.0, 'SEP-12', 'Kolkata', '60 & above', 'Male', 'Daily Worker', 'Rs. 1 lakh or less', '3 or 4', 'Below Graduate', 2.0, 'Worsen', 'Will Worsen', 'Somewhat worse off', None, 'Increased', 'Increase', 'Increased', 'Increase', 'Worsen', 'Will worsen', 'Gone up', 'Will go up', 'More than last year', 'More than current year'), (7, 8.0, 10.0, 'SEP-12', 'Mumbai', '30-39', 'Male', 'Self employed/Business', 'Rs. 1 - 3 lakhs', '3 or 4', 'Below Graduate', 1.0, 'Remained the same', 'Will Improve', 'Difficult to say', 'Will Remain the Same', 'Remained the same', 'Increase', 'Increased', 'Increase', 'Remained the same', 'Will Remain the Same', 'Gone up', 'Will go up', 'More than last year', 'More than current year')  ... displaying 10 of 5124 total bound parameter sets ...  (5122, 5124.0, 10.0, 'SEP-12', 'Kolkata', '40-59', 'Male', 'Employed', 'Rs. 5 lakhs or more', '3 or 4', 'Graduate & above', 1.0, 'Improved', 'Will Improve', 'Somewhat better off', 'Will be better off', 'Increased', 'Increase', 'Increased', 'Increase', 'Improved', 'Will improve', 'Gone up', 'Will go up', 'More than last year', 'More than current year'), (5123, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None))
2021-02-22 23:31:44,762 INFO sqlalchemy.engine.base.Engine COMMIT
2021-02-22 23:31:44,766 INFO sqlalchemy.engine.base.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name
2021-02-22 23:31:44,766 INFO sqlalchemy.engine.base.Engine ()